/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo{
    private var real: Int=0
    private var imaginario: Int=0
    fun inicializar(real: Int, imaginario: Int){ //esta variable no es igual a la definida recién
        this.real=real                              //this es 
        this.imaginario=imaginario
    }
    
    override fun toString(): String {
        return "(${real},${imaginario})" //el signo $ devuelve el valor guardado
    }

}
fun main() {
    var complejo: Complejo
    complejo=Complejo()
    complejo.inicializar(3,4)
    println("mi número complejo es ${complejo.toString()}")
}